# Copyright (C) 2026 Julian Decker
# Copyright (C) Agustín Giménez Bernad (gusmanb), original LogicAnalyzer
#
# Part of PiPiLogicAnalyzer, a port and extension of his software;
# the changes are described in docs/improvements.md and CHANGELOG.md.
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Data model of a capture: channels, sessions, bursts and trigger definitions.

Port of ``SharedDriver/AnalyzerChannel.cs``, ``CaptureSession.cs`` and
``BurstInfo.cs`` from the original C# software.

Samples are stored as ``numpy`` ``uint8`` arrays (one entry per sample, value 0
or 1).  The original implementation used ``byte[]`` and iterated sample by
sample in managed code; keeping the data in numpy lets every consumer
(rendering, measurements, export, decoders) work on vectorised operations
instead.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Optional, Sequence

import numpy as np


class TriggerType(IntEnum):
    """Trigger modes understood by the firmware (values are wire values)."""

    EDGE = 0
    COMPLEX = 1
    FAST = 2
    BLAST = 3
    #: Test signals generated by the board (or computed by the application);
    #: ``trigger_pattern`` selects the pattern.
    SIMULATION = 4
    #: Edge trigger that also drives the trigger output: the board triggering a multi device set
    #: (firmware of this project, capability ``EDGE_TRIGGER_OUT``).
    EDGE_OUT = 5
    #: No trigger, the capture starts at once (capability ``IMMEDIATE_TRIGGER``, DSLogic)
    IMMEDIATE = 6

    @property
    def label(self) -> str:
        return {
            TriggerType.EDGE: "Edge",
            TriggerType.COMPLEX: "Complex",
            TriggerType.FAST: "Fast",
            TriggerType.BLAST: "Blast",
            TriggerType.SIMULATION: "Simulation",
            TriggerType.EDGE_OUT: "Edge (trigger output)",
            TriggerType.IMMEDIATE: "None",
        }[self]


@dataclass(eq=False)
class AnalyzerChannel:
    """A single captured channel.

    Equality is identity based on purpose: the generated ``__eq__`` would
    compare the ``samples`` arrays element-wise, which raises for numpy arrays
    ("truth value of an array is ambiguous") as soon as two channels share the
    same metadata.  The C# original compared channel references as well.
    """

    channel_number: int = 0
    channel_name: str = ""
    channel_color: Optional[int] = None
    hidden: bool = False
    samples: Optional[np.ndarray] = None

    @property
    def textual_channel_number(self) -> str:
        return f"Channel {self.channel_number + 1}"

    @property
    def display_name(self) -> str:
        if self.channel_name and self.channel_name.strip():
            return self.channel_name
        return self.textual_channel_number

    def clone(self) -> "AnalyzerChannel":
        return AnalyzerChannel(
            channel_number=self.channel_number,
            channel_name=self.channel_name,
            channel_color=self.channel_color,
            hidden=self.hidden,
            samples=None if self.samples is None else self.samples.copy(),
        )

    def __str__(self) -> str:  # pragma: no cover - convenience only
        return self.display_name


@dataclass
class BurstInfo:
    """Timing information of a burst captured in "burst mode"."""

    burst_sample_start: int = 0
    burst_sample_end: int = 0
    burst_sample_gap: int = 0
    burst_time_gap: int = 0  # nanoseconds

    def get_time(self) -> str:
        gap = self.burst_time_gap
        if gap < 1_000:
            return f"{gap} ns"
        if gap < 1_000_000:
            return f"{gap / 1_000.0:.3f} µs"
        if gap < 1_000_000_000:
            return f"{gap / 1_000_000.0:.3f} ms"
        return f"{gap / 1_000_000_000.0:.3f} s"

    def __str__(self) -> str:
        return (
            f"Burst: {self.burst_sample_start} to {self.burst_sample_end}\n"
            f"Gap: {self.get_time()} ({self.burst_sample_gap} samples)"
        )


@dataclass(eq=False)
class CaptureSession:
    """Everything needed to request a capture and to describe its result.

    Identity based equality, for the same reason as :class:`AnalyzerChannel`.
    """

    frequency: int = 100_000_000
    pre_trigger_samples: int = 512
    post_trigger_samples: int = 1024
    loop_count: int = 0
    measure_bursts: bool = False
    capture_channels: list[AnalyzerChannel] = field(default_factory=list)
    bursts: Optional[list[BurstInfo]] = None
    trigger_type: TriggerType = TriggerType.EDGE
    trigger_channel: int = 0
    trigger_inverted: bool = False
    trigger_bit_count: int = 0
    trigger_pattern: int = 0
    #: ``"buffer"`` or ``"stream"`` (``ACQUISITION_*`` of the driver base), devices with both modes
    acquisition_mode: str = "buffer"
    #: Input threshold in volts for devices with an adjustable threshold, ``None``: device default
    threshold_voltage: Optional[float] = None

    @property
    def total_samples(self) -> int:
        return self.post_trigger_samples * (self.loop_count + 1) + self.pre_trigger_samples

    def clone(self) -> "CaptureSession":
        new = copy.copy(self)
        new.capture_channels = [c.clone() for c in self.capture_channels]
        new.bursts = None if self.bursts is None else [copy.copy(b) for b in self.bursts]
        return new

    def clone_settings(self) -> "CaptureSession":
        """Clone without sample data (used to persist the capture settings)."""
        new = self.clone()
        for channel in new.capture_channels:
            channel.samples = None
        new.bursts = None
        return new

    @property
    def channel_numbers(self) -> list[int]:
        return [c.channel_number for c in self.capture_channels]

    def sample_count(self) -> int:
        """Actual number of samples held by the channels (may differ from
        :attr:`total_samples` after editing operations)."""
        for channel in self.capture_channels:
            if channel.samples is not None:
                return int(channel.samples.shape[0])
        return 0

    def trigger_description(self) -> str:
        if self.trigger_type == TriggerType.SIMULATION:
            from ..core.simulation import SimulationPattern

            try:
                return SimulationPattern(self.trigger_pattern).label
            except ValueError:
                return f"Pattern {self.trigger_pattern}"
        if self.trigger_type == TriggerType.IMMEDIATE:
            return "Immediate"
        if self.trigger_type in (TriggerType.EDGE, TriggerType.BLAST, TriggerType.EDGE_OUT):
            return "Negative" if self.trigger_inverted else "Positive"
        return "".join(
            "1" if self.trigger_pattern & (1 << bit) else "0"
            for bit in range(self.trigger_bit_count)
        )


def build_channels(numbers: Sequence[int], names: Optional[Sequence[str]] = None) -> list[AnalyzerChannel]:
    """Small helper used by dialogs and tests."""
    names = list(names) if names is not None else [""] * len(numbers)
    return [
        AnalyzerChannel(channel_number=int(number), channel_name=name)
        for number, name in zip(numbers, names)
    ]
