# Copyright (C) 2026 Julian Decker
# Copyright (C) Agustín Giménez Bernad (gusmanb), original LogicAnalyzer
#
# Part of openSciLab, a port and extension of his software;
# the changes are described in docs/improvements.md and CHANGELOG.md.
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Data model of a capture: channels, sessions, bursts and trigger definitions.

Port of ``SharedDriver/AnalyzerChannel.cs``, ``CaptureSession.cs`` and
``BurstInfo.cs`` from the original C# software.

Samples are stored as ``numpy`` ``uint8`` arrays (one entry per sample, value 0
or 1).  The original implementation used ``byte[]`` and iterated sample by
sample in managed code; keeping the data in numpy lets every consumer
(rendering, measurements, export, decoders) work on vectorised operations
instead.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass, field
from enum import Enum, IntEnum
from typing import Any, Optional, Sequence

import numpy as np


class TriggerType(IntEnum):
    """Trigger modes understood by the firmware (values are wire values)."""

    EDGE = 0
    COMPLEX = 1
    FAST = 2
    BLAST = 3
    #: Test signals generated by the board (or computed by the application);
    #: ``trigger_pattern`` selects the pattern.
    SIMULATION = 4
    #: Edge trigger that also drives the trigger output: the board triggering a multi device set
    #: (firmware of this project, capability ``EDGE_TRIGGER_OUT``).
    EDGE_OUT = 5
    #: No trigger, the capture starts at once (capability ``IMMEDIATE_TRIGGER``, DSLogic)
    IMMEDIATE = 6
    #: Trigger sequence of ``CaptureSession.trigger_sequence``: stages of patterns, edges, pulse
    #: widths and gaps (capability ``TRIGGER_SEQUENCE``, or evaluated by the application on a stream)
    SEQUENCE = 7

    @property
    def label(self) -> str:
        return {
            TriggerType.EDGE: "Edge",
            TriggerType.COMPLEX: "Complex",
            TriggerType.FAST: "Fast",
            TriggerType.BLAST: "Blast",
            TriggerType.SIMULATION: "Simulation",
            TriggerType.EDGE_OUT: "Edge (trigger output)",
            TriggerType.IMMEDIATE: "None",
            TriggerType.SEQUENCE: "Sequence",
        }[self]


class EdgeKind(str, Enum):
    RISING = "rising"
    FALLING = "falling"
    ANY = "any"


class ConditionKind(str, Enum):
    """What a stage of a trigger sequence waits for."""

    #: The channels of ``mask`` have the levels of ``value``
    PATTERN = "pattern"
    #: An edge of ``edge`` on ``channel``
    EDGE = "edge"
    #: A pulse on ``channel`` whose width lies in ``[min_ns, max_ns]`` (either may be ``None``);
    #: ``edge`` RISING: a high pulse, FALLING: a low pulse, ANY: either. It is recognised at its end.
    PULSE = "pulse"
    #: ``channel`` stays unchanged for at least ``min_ns`` (timeout); recognised once the time is over
    GAP = "gap"


@dataclass
class TriggerCondition:
    kind: ConditionKind = ConditionKind.EDGE
    #: Channel number of EDGE, PULSE and GAP
    channel: int = 0
    edge: EdgeKind = EdgeKind.RISING
    #: PATTERN: bit ``n`` is channel number ``n``; channels outside the mask are "don't care"
    mask: int = 0
    value: int = 0
    min_ns: Optional[int] = None
    max_ns: Optional[int] = None

    def describe(self) -> str:
        name = f"CH{self.channel + 1}"
        if self.kind == ConditionKind.PATTERN:
            bits = [n for n in range(64) if self.mask >> n & 1]
            return "pattern " + (" ".join(f"CH{n + 1}={self.value >> n & 1}" for n in bits) or "(any)")
        if self.kind == ConditionKind.EDGE:
            return f"{self.edge.value} edge on {name}"
        if self.kind == ConditionKind.PULSE:
            level = {EdgeKind.RISING: "high", EdgeKind.FALLING: "low", EdgeKind.ANY: "any"}[self.edge]
            limits = []
            if self.min_ns is not None:
                limits.append(f"≥ {self.min_ns} ns")
            if self.max_ns is not None:
                limits.append(f"≤ {self.max_ns} ns")
            return f"{level} pulse on {name}" + (f" ({', '.join(limits)})" if limits else "")
        return f"no edge on {name} for {self.min_ns or 0} ns"


@dataclass
class TriggerStage:
    condition: TriggerCondition = field(default_factory=TriggerCondition)
    #: Occurrences of the condition needed to complete the stage
    count: int = 1
    #: The stage has to complete within this time after the previous one, else the sequence
    #: starts again at the first stage (``None``: no limit; ignored for the first stage)
    within_ns: Optional[int] = None


@dataclass
class TriggerSequence:
    """Stages completed one after the other; the capture triggers at the end of the last one."""

    stages: list[TriggerStage] = field(default_factory=list)

    def describe(self) -> str:
        parts = []
        for index, stage in enumerate(self.stages):
            text = stage.condition.describe()
            if stage.count > 1:
                text += f" ×{stage.count}"
            if index and stage.within_ns is not None:
                text += f" within {stage.within_ns} ns"
            parts.append(text)
        return " → ".join(parts) or "(empty)"


class BusFormat(str, Enum):
    HEX = "hex"
    DECIMAL = "decimal"
    SIGNED = "signed"
    BINARY = "binary"
    ASCII = "ascii"


@dataclass
class BusDefinition:
    """Channels shown together as one value (a bus or a group)."""

    name: str = "Bus"
    #: Channel numbers, least significant bit first
    channels: list[int] = field(default_factory=list)
    format: BusFormat = BusFormat.HEX
    #: Names shown instead of values (a symbol table), e.g. ``{0xD020: "BORDER"}``
    symbols: dict[int, str] = field(default_factory=dict)
    color: Optional[int] = None


@dataclass(eq=False)
class AnalyzerChannel:
    """A single captured channel.

    Equality is identity based on purpose: the generated ``__eq__`` would
    compare the ``samples`` arrays element-wise, which raises for numpy arrays
    ("truth value of an array is ambiguous") as soon as two channels share the
    same metadata.  The C# original compared channel references as well.
    """

    channel_number: int = 0
    channel_name: str = ""
    channel_color: Optional[int] = None
    hidden: bool = False
    samples: Optional[np.ndarray] = None

    @property
    def textual_channel_number(self) -> str:
        return f"Channel {self.channel_number + 1}"

    @property
    def display_name(self) -> str:
        if self.channel_name and self.channel_name.strip():
            return self.channel_name
        return self.textual_channel_number

    def clone(self, with_samples: bool = True) -> "AnalyzerChannel":
        return AnalyzerChannel(
            channel_number=self.channel_number,
            channel_name=self.channel_name,
            channel_color=self.channel_color,
            hidden=self.hidden,
            samples=None if self.samples is None or not with_samples else self.samples.copy(),
        )

    def __str__(self) -> str:  # pragma: no cover - convenience only
        return self.display_name


@dataclass(eq=False)
class AnalogChannel:
    """An analog channel: raw ``int16`` samples, ``volts = raw * scale + offset``.

    ``raw`` may be a memory-mapped array that fills while a large capture is transferred
    (progressive transfer); ``length`` is the number of samples of the channel even before they
    arrived. ``rate`` is the channel's own sample rate, ``None``: the rate of the session.
    """

    channel_number: int = 0
    channel_name: str = ""
    unit: str = "V"
    scale: float = 1.0
    offset: float = 0.0
    raw: Optional[np.ndarray] = None
    rate: Optional[int] = None
    channel_color: Optional[int] = None
    hidden: bool = False
    #: samples of the channel (``len(raw)`` once loaded)
    length: Optional[int] = None

    @property
    def display_name(self) -> str:
        return self.channel_name.strip() if self.channel_name and self.channel_name.strip() else \
            f"Analog {self.channel_number + 1}"

    @property
    def sample_count(self) -> int:
        if self.length is not None:
            return int(self.length)
        return 0 if self.raw is None else int(len(self.raw))

    def volts(self, start: int = 0, end: Optional[int] = None) -> np.ndarray:
        """The samples ``[start, end)`` in the channel's unit (``float64``)."""
        if self.raw is None:
            return np.zeros(0, dtype=np.float64)
        return np.asarray(self.raw[start:end], dtype=np.float64) * self.scale + self.offset

    def to_raw(self, values: np.ndarray) -> np.ndarray:
        """Values in the channel's unit as raw ``int16`` (clipped)."""
        raw = np.round((np.asarray(values, dtype=np.float64) - self.offset) / (self.scale or 1.0))
        return np.clip(raw, -32768, 32767).astype(np.int16)

    @staticmethod
    def from_volts(values, channel_number: int = 0, channel_name: str = "", unit: str = "V",
                   rate: Optional[int] = None, low: Optional[float] = None,
                   high: Optional[float] = None) -> "AnalogChannel":
        """A channel holding ``values`` with a scale that uses the ``int16`` range for
        ``low``..``high`` (default: the range of the values)."""
        values = np.asarray(values, dtype=np.float64)
        low = float(values.min()) if low is None and values.size else (low or 0.0)
        high = float(values.max()) if high is None and values.size else (high if high is not None else 1.0)
        if high <= low:
            high = low + 1.0
        offset = (high + low) / 2.0
        scale = (high - low) / 65000.0
        channel = AnalogChannel(channel_number=channel_number, channel_name=channel_name, unit=unit,
                                scale=scale, offset=offset, rate=rate)
        channel.raw = channel.to_raw(values)
        return channel

    def clone(self, with_samples: bool = True) -> "AnalogChannel":
        return AnalogChannel(
            channel_number=self.channel_number, channel_name=self.channel_name, unit=self.unit, scale=self.scale,
            offset=self.offset, raw=None if self.raw is None or not with_samples else np.array(self.raw, copy=True),
            rate=self.rate, channel_color=self.channel_color, hidden=self.hidden,
            length=self.length if with_samples else None,
        )


@dataclass
class BurstInfo:
    """Timing information of a burst captured in "burst mode"."""

    burst_sample_start: int = 0
    burst_sample_end: int = 0
    burst_sample_gap: int = 0
    burst_time_gap: int = 0  # nanoseconds

    def get_time(self) -> str:
        gap = self.burst_time_gap
        if gap < 1_000:
            return f"{gap} ns"
        if gap < 1_000_000:
            return f"{gap / 1_000.0:.3f} µs"
        if gap < 1_000_000_000:
            return f"{gap / 1_000_000.0:.3f} ms"
        return f"{gap / 1_000_000_000.0:.3f} s"

    def __str__(self) -> str:
        return (
            f"Burst: {self.burst_sample_start} to {self.burst_sample_end}\n"
            f"Gap: {self.get_time()} ({self.burst_sample_gap} samples)"
        )


@dataclass(eq=False)
class CaptureSession:
    """Everything needed to request a capture and to describe its result.

    Identity based equality, for the same reason as :class:`AnalyzerChannel`.
    """

    frequency: int = 100_000_000
    pre_trigger_samples: int = 512
    post_trigger_samples: int = 1024
    loop_count: int = 0
    measure_bursts: bool = False
    capture_channels: list[AnalyzerChannel] = field(default_factory=list)
    bursts: Optional[list[BurstInfo]] = None
    trigger_type: TriggerType = TriggerType.EDGE
    trigger_channel: int = 0
    trigger_inverted: bool = False
    trigger_bit_count: int = 0
    trigger_pattern: int = 0
    #: Bits of ``trigger_pattern`` that count (``None``: all); the others are "don't care" on devices
    #: that know it, 0 on the others
    trigger_mask: Optional[int] = None
    #: ``"buffer"`` or ``"stream"`` (``ACQUISITION_*`` of the driver base), devices with both modes
    acquisition_mode: str = "buffer"
    #: Input threshold in volts for devices with an adjustable threshold, ``None``: device default
    threshold_voltage: Optional[float] = None
    #: Stream until stopped, keeping only the latest ``pre + post`` samples (devices with
    #: ``CAPABILITY_CONTINUOUS_STREAM``)
    continuous: bool = False
    #: Stream into memory-mapped files instead of memory, limited by the free disk space
    to_disk: bool = False
    #: Stages of ``TriggerType.SEQUENCE``
    trigger_sequence: Optional[TriggerSequence] = None
    #: The application evaluates the trigger on a stream instead of the device (any device that
    #: streams); the capture keeps ``pre_trigger_samples`` before and ``post_trigger_samples`` after it
    software_trigger: bool = False
    #: State mode: samples are taken on the edges of this channel (external clock) instead of the
    #: internal rate (capability ``STATE_MODE``); ``None``: timing mode
    clock_channel: Optional[int] = None
    clock_edge: EdgeKind = EdgeKind.RISING
    #: Buses and groups shown with the capture
    buses: list[BusDefinition] = field(default_factory=list)
    #: Analog channels (devices with ``CAPABILITY_ANALOG``), on the rate of the session unless
    #: they name their own
    analog_channels: list[AnalogChannel] = field(default_factory=list)
    #: State mode: the time of every state in microseconds from the first one, when the device
    #: stamps them (``None``: unknown, only the order of the states)
    state_times: Optional[np.ndarray] = None
    #: A large capture still arriving (progressive transfer, see ``core/overview.py``); ``None``
    #: once complete. Not saved.
    progressive: Any = None

    @property
    def total_samples(self) -> int:
        return self.post_trigger_samples * (self.loop_count + 1) + self.pre_trigger_samples

    def clone(self) -> "CaptureSession":
        new = copy.copy(self)
        new.capture_channels = [c.clone() for c in self.capture_channels]
        new.bursts = None if self.bursts is None else [copy.copy(b) for b in self.bursts]
        new.trigger_sequence = copy.deepcopy(self.trigger_sequence)
        new.buses = copy.deepcopy(self.buses)
        new.analog_channels = [channel.clone() for channel in self.analog_channels]
        new.state_times = None if self.state_times is None else np.array(self.state_times, copy=True)
        new.progressive = None
        return new

    def clone_settings(self) -> "CaptureSession":
        """Clone without sample data (used to persist the capture settings)."""
        new = copy.copy(self)
        # (the channels of this session are not touched: another thread may be reading them)
        new.capture_channels = [channel.clone(with_samples=False) for channel in self.capture_channels]
        new.bursts = None
        new.trigger_sequence = copy.deepcopy(self.trigger_sequence)
        new.buses = copy.deepcopy(self.buses)
        new.analog_channels = [channel.clone(with_samples=False) for channel in self.analog_channels]
        new.state_times = None
        new.progressive = None
        return new

    @property
    def is_state_capture(self) -> bool:
        return self.clock_channel is not None

    @property
    def channel_numbers(self) -> list[int]:
        return [c.channel_number for c in self.capture_channels]

    def sample_count(self) -> int:
        """Actual number of samples held by the channels (may differ from
        :attr:`total_samples` after editing operations)."""
        for channel in self.capture_channels:
            if channel.samples is not None:
                return int(channel.samples.shape[0])
        # Only analog channels: their samples on the rate of the session.
        for channel in self.analog_channels:
            if channel.sample_count:
                if channel.rate and channel.rate != self.frequency:
                    return int(channel.sample_count * self.frequency / channel.rate)
                return channel.sample_count
        return 0

    def trigger_description(self) -> str:
        if self.trigger_type == TriggerType.SIMULATION:
            from ..core.simulation import SimulationPattern

            try:
                return SimulationPattern(self.trigger_pattern).label
            except ValueError:
                return f"Pattern {self.trigger_pattern}"
        if self.trigger_type == TriggerType.IMMEDIATE:
            return "Immediate"
        if self.trigger_type == TriggerType.SEQUENCE:
            return self.trigger_sequence.describe() if self.trigger_sequence else "(empty)"
        if self.trigger_type in (TriggerType.EDGE, TriggerType.BLAST, TriggerType.EDGE_OUT):
            return "Negative" if self.trigger_inverted else "Positive"
        return "".join(
            "X" if self.trigger_mask is not None and not self.trigger_mask & (1 << bit)
            else "1" if self.trigger_pattern & (1 << bit) else "0"
            for bit in range(self.trigger_bit_count)
        )


def build_channels(numbers: Sequence[int], names: Optional[Sequence[str]] = None) -> list[AnalyzerChannel]:
    """Small helper used by dialogs and tests."""
    names = list(names) if names is not None else [""] * len(numbers)
    return [
        AnalyzerChannel(channel_number=int(number), channel_name=name)
        for number, name in zip(numbers, names)
    ]
