# Copyright (C) 2026 Julian Decker
# Copyright (C) Agustín Giménez Bernad (gusmanb), original LogicAnalyzer
#
# Part of PiPiLogicAnalyzer, a port and extension of his software;
# the changes are described in docs/improvements.md and CHANGELOG.md.
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Manual sample composition.

Ports of ``Dialogs/CreateSamplesDialog``, ``Dialogs/SignalComposerDialog`` and
``Controls/ChannelSampleMaker``: each channel gets a Signal Description Language
definition, which is expanded into samples.

The composer previews the signal while it is typed and reports parse errors
inline instead of only when the dialog is closed.
"""

from __future__ import annotations

from typing import Optional, Sequence

import numpy as np
from PySide6.QtCore import QRectF, Qt
from PySide6.QtGui import QColor, QFont, QPainter, QPen
from PySide6.QtWidgets import (
    QDialog,
    QFormLayout,
    QFrame,
    QHBoxLayout,
    QLabel,
    QPlainTextEdit,
    QPushButton,
    QScrollArea,
    QSpinBox,
    QVBoxLayout,
    QWidget,
)

from ...core import colors
from ...sdl import SDLError, TokenizedSDL, samples_from_source
from .. import messages
from ..theme import INPUT, TEXT_MUTED, set_role
from ..icons import set_icon
from .common import InlineMessage, button_box, dialog_layout, hint

DEFAULT_SDL = "$0;h10;l10;"

SDL_HELP = """<b>Signal Description Language</b><br>
<tt>$0</tt> / <tt>$1</tt> initial level &nbsp;&nbsp;
<tt>h10</tt> 10 samples high &nbsp;&nbsp;
<tt>l10</tt> 10 samples low<br>
<tt>!5</tt> 5 samples inverted &nbsp;&nbsp;
<tt>=5</tt> 5 samples unchanged &nbsp;&nbsp;
<tt>[name]</tt> expand a group<br>
<tt>{l2,h2}10</tt> repeat a group &nbsp;&nbsp;
<tt>{&lt;0&gt;,l2,h1}1</tt> define the group "0"<br>
<tt>b0x55</tt> byte LSB first &nbsp;&nbsp; <tt>B0x55</tt> byte MSB first &nbsp;&nbsp;
<tt>s"text"</tt> ASCII string<br>
Bytes and strings need the groups <tt>0</tt> and <tt>1</tt> to be defined.
Tokens are separated by <tt>;</tt>, <tt>//</tt> and <tt>/* */</tt> are comments.
"""


class SignalPreview(QWidget):
    """Draws the samples generated by an SDL definition."""

    def __init__(self, color: QColor, parent: Optional[QWidget] = None) -> None:
        super().__init__(parent)
        self.color = color
        self.samples: Optional[np.ndarray] = None
        self.setMinimumHeight(46)

    def set_samples(self, samples: Optional[np.ndarray]) -> None:
        self.samples = samples
        self.update()

    def paintEvent(self, event) -> None:  # noqa: N802 - Qt naming
        painter = QPainter(self)
        bounds = QRectF(0, 0, self.width(), self.height())
        painter.fillRect(bounds, QColor(INPUT))

        if self.samples is None or self.samples.size == 0:
            painter.setPen(QPen(QColor(TEXT_MUTED)))
            painter.drawText(bounds, Qt.AlignCenter, "Invalid definition - no samples")
            return

        samples = self.samples
        width = max(self.width(), 1)
        if samples.size > width:
            indexes = np.linspace(0, samples.size - 1, width).astype(np.int64)
            samples = samples[indexes]

        sample_width = width / samples.size
        top = bounds.height() * 0.2
        bottom = bounds.height() * 0.8

        painter.setPen(QPen(self.color, 2))
        previous = None
        for index, value in enumerate(samples):
            x = index * sample_width
            y = top if value else bottom
            if previous is not None and previous != value:
                painter.drawLine(x, top, x, bottom)
            painter.drawLine(x, y, x + sample_width, y)
            previous = value


class SignalComposerDialog(QDialog):
    """Edits the SDL definition of one channel."""

    def __init__(
        self,
        source: str,
        color: QColor,
        total_samples: int,
        parent: Optional[QWidget] = None,
    ) -> None:
        super().__init__(parent)
        self.setWindowTitle("Signal composer")
        self.resize(740, 520)
        self.total_samples = total_samples
        self.source = source

        layout = dialog_layout(self)

        self.editor = QPlainTextEdit(source, self)
        self.editor.setPlaceholderText(DEFAULT_SDL)
        font = QFont("Menlo")
        font.setStyleHint(QFont.Monospace)
        self.editor.setFont(font)
        self.editor.textChanged.connect(self._update_preview)
        layout.addWidget(self.editor, 1)

        self.preview = SignalPreview(color, self)
        layout.addWidget(self.preview)

        self.status = QLabel(self)
        self.status.setWordWrap(True)
        layout.addWidget(self.status)

        help_label = hint(SDL_HELP, self)
        layout.addWidget(help_label)

        buttons = button_box(self, "Apply", icon="check")
        buttons.accepted.connect(self._accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)

        self._update_preview()

    def _parse(self) -> Optional[np.ndarray]:
        text = self.editor.toPlainText().strip()
        if not text:
            self.status.setText("The definition is empty.")
            set_role(self.status, "warning")
            return None
        try:
            samples = TokenizedSDL(text).to_samples()
        except SDLError as error:
            self.status.setText(str(error))
            set_role(self.status, "error")
            return None
        self.status.setText(
            f"{samples.size:,} samples generated "
            f"({'padded' if samples.size < self.total_samples else 'truncated'} "
            f"to {self.total_samples:,})"
            if samples.size != self.total_samples
            else f"{samples.size:,} samples generated"
        )
        set_role(self.status, "success")
        return samples

    def _update_preview(self) -> None:
        samples = self._parse()
        self.preview.set_samples(samples)

    def _accept(self) -> None:
        if self._parse() is None and not messages.confirm(
            self,
            "Signal composer",
            "The definition contains errors and does not generate samples.",
            "Keep anyway",
        ):
            return
        self.source = self.editor.toPlainText()
        self.accept()


class ChannelSampleMaker(QFrame):
    """One row of the sample creation dialog."""

    def __init__(
        self, channel_number: int, channel_name: str, total_samples: int, parent: Optional[QWidget] = None
    ) -> None:
        super().__init__(parent)
        set_role(self, "card")
        self.channel_number = channel_number
        self.channel_name = channel_name
        self.total_samples = total_samples
        self.source = DEFAULT_SDL

        layout = QHBoxLayout(self)
        layout.setContentsMargins(8, 6, 8, 6)

        label = QLabel(
            f"<b>Channel {channel_number + 1}</b>"
            + (f"<br><span style='color:{TEXT_MUTED}'>{channel_name}</span>" if channel_name else ""),
            self,
        )
        label.setFixedWidth(110)
        layout.addWidget(label)

        self.preview = SignalPreview(colors.get_color(channel_number), self)
        layout.addWidget(self.preview, 1)

        edit_button = QPushButton("Edit...", self)
        set_icon(edit_button, "pencil")
        edit_button.setToolTip("Describe the signal of this channel")
        edit_button.clicked.connect(self.edit)
        layout.addWidget(edit_button)

        self.refresh()

    def set_total_samples(self, total_samples: int) -> None:
        self.total_samples = total_samples
        self.refresh()

    def edit(self) -> None:
        dialog = SignalComposerDialog(
            self.source, colors.get_color(self.channel_number), self.total_samples, self
        )
        if dialog.exec():
            self.source = dialog.source
            self.refresh()

    def samples(self) -> Optional[np.ndarray]:
        try:
            return samples_from_source(self.source, self.total_samples)
        except SDLError:
            return None

    def refresh(self) -> None:
        self.preview.set_samples(self.samples())


class CreateSamplesDialog(QDialog):
    """Creates (or inserts) samples for every channel of a capture."""

    def __init__(
        self,
        channel_numbers: Sequence[int],
        channel_names: Sequence[str],
        max_samples: int,
        initial_samples: int,
        insert_mode: bool = False,
        parent: Optional[QWidget] = None,
    ) -> None:
        super().__init__(parent)
        self.setWindowTitle("Insert samples" if insert_mode else "New capture - signals")
        self.resize(800, 580)
        self.samples: Optional[list[np.ndarray]] = None

        layout = dialog_layout(self)
        layout.addWidget(
            hint(
                "Describe the signal of every channel with the Signal Description Language; "
                "press Edit... next to a channel to change it.",
                self,
            )
        )

        form = QFormLayout()
        self.samples_box = QSpinBox(self)
        self.samples_box.setRange(1, max(max_samples, 1))
        self.samples_box.setValue(max(min(initial_samples, max_samples), 1))
        self.samples_box.setGroupSeparatorShown(True)
        self.samples_box.setSuffix(" samples")
        self.samples_box.valueChanged.connect(self._on_samples_changed)
        form.addRow("Insert:" if insert_mode else "Length:", self.samples_box)
        layout.addLayout(form)

        scroll = QScrollArea(self)
        scroll.setWidgetResizable(True)
        content = QWidget(scroll)
        content_layout = QVBoxLayout(content)
        content_layout.setContentsMargins(0, 0, 4, 0)
        content_layout.setSpacing(6)

        self.makers: list[ChannelSampleMaker] = []
        for number, name in zip(channel_numbers, channel_names):
            maker = ChannelSampleMaker(number, name, self.samples_box.value(), content)
            content_layout.addWidget(maker)
            self.makers.append(maker)
        content_layout.addStretch(1)

        scroll.setWidget(content)
        layout.addWidget(scroll, 1)

        self.message = InlineMessage(self)
        layout.addWidget(self.message)

        buttons = button_box(self, "Insert samples" if insert_mode else "Create capture", icon="check")
        buttons.accepted.connect(self._accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)

    def _on_samples_changed(self, value: int) -> None:
        self.message.clear()
        for maker in self.makers:
            maker.set_total_samples(value)

    def _accept(self) -> None:
        result: list[np.ndarray] = []
        for maker in self.makers:
            samples = maker.samples()
            if samples is None:
                self.message.show_error(
                    f"Channel {maker.channel_number + 1} has an invalid signal definition; "
                    "press Edit... to correct it."
                )
                return
            result.append(samples)

        self.samples = result
        self.accept()
