# Copyright (C) 2026 Julian Decker
# Copyright (C) Agustín Giménez Bernad (gusmanb), original LogicAnalyzer
#
# Part of PiPiLogicAnalyzer 7, a port and extension of his software;
# the changes are described in docs/improvements.md and CHANGELOG.md.
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Simulated capture: test signals generated by the board or by the application."""

from __future__ import annotations

from typing import Optional

from PySide6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QDialog,
    QFormLayout,
    QGroupBox,
    QSpinBox,
    QVBoxLayout,
    QWidget,
)

from ...core import simulation
from ...core.simulation import SimulationPattern
from ...driver.base import AnalyzerDriverBase
from ...driver.models import AnalyzerChannel, CaptureSession, TriggerType
from .common import Banner, button_box, dialog_layout, hint

PROTOCOL_CHANNEL_NAMES = ["UART TX", "SPI CLK", "SPI MOSI", "SPI CS", "I2C SCL", "I2C SDA"]
MAX_SIMULATED_CHANNELS = 32


class SimulationDialog(QDialog):
    def __init__(
        self,
        driver: AnalyzerDriverBase,
        on_board: bool,
        board_connected: bool,
        parent: Optional[QWidget] = None,
    ) -> None:
        super().__init__(parent)
        self.driver = driver
        self.session: Optional[CaptureSession] = None

        self.setWindowTitle("Simulated capture")
        self.resize(540, 480)
        layout = dialog_layout(self)

        if on_board:
            kind, source = "info", (
                "<b>Generated by the board.</b> The signals are transferred like a real capture, "
                "which tests the firmware, the USB/WiFi link and the application. No signals need "
                "to be connected."
            )
        elif board_connected:
            kind, source = "warning", (
                "<b>Computed on this computer.</b> The firmware of the connected board cannot "
                "simulate; flash the firmware of this project to test the board as well."
            )
        else:
            kind, source = "info", (
                "<b>Computed on this computer.</b> No board is connected."
            )
        self.source_banner = Banner(kind, self)
        self.source_banner.set_message(source)
        self.source_label = self.source_banner.label
        layout.addWidget(self.source_banner)

        group = QGroupBox("Signals", self)
        group_layout = QVBoxLayout(group)
        form = QFormLayout()
        self.pattern_box = QComboBox(group)
        for pattern in SimulationPattern:
            self.pattern_box.addItem(pattern.label, int(pattern))
        self.pattern_box.setCurrentIndex(self.pattern_box.findData(int(SimulationPattern.PROTOCOLS)))
        form.addRow("Pattern:", self.pattern_box)

        self.channels_box = QSpinBox(group)
        self.channels_box.setRange(1, max(1, min(driver.channel_count, MAX_SIMULATED_CHANNELS)))
        self.channels_box.setValue(min(8, self.channels_box.maximum()))
        form.addRow("Channels:", self.channels_box)

        self.frequency_box = QSpinBox(group)
        self.frequency_box.setGroupSeparatorShown(True)
        self.frequency_box.setRange(1_000, max(driver.max_frequency, 1_000))
        self.frequency_box.setSingleStep(100_000)
        self.frequency_box.setValue(min(1_000_000, self.frequency_box.maximum()))
        self.frequency_box.setSuffix(" Hz")
        form.addRow("Sampling frequency:", self.frequency_box)

        self.samples_box = QSpinBox(group)
        self.samples_box.setGroupSeparatorShown(True)
        self.samples_box.setSingleStep(1_000)
        form.addRow("Samples:", self.samples_box)
        group_layout.addLayout(form)

        self.description = hint("", group)
        group_layout.addWidget(self.description)
        layout.addWidget(group)

        self.decoders_box = QCheckBox("Add UART, SPI and I2C decoders for the channels", self)
        self.decoders_box.setChecked(True)
        layout.addWidget(self.decoders_box)
        layout.addStretch(1)

        buttons = button_box(self, "Start simulation", icon="play")
        buttons.accepted.connect(self._accept)
        buttons.rejected.connect(self.reject)
        layout.addWidget(buttons)

        self.pattern_box.currentIndexChanged.connect(self._refresh)
        self.channels_box.valueChanged.connect(self._refresh)
        self.frequency_box.valueChanged.connect(self._refresh)
        self._refresh()
        self.samples_box.setValue(min(20_000, self.samples_box.maximum()))

    @property
    def pattern(self) -> SimulationPattern:
        return SimulationPattern(int(self.pattern_box.currentData()))

    @property
    def channel_count(self) -> int:
        return self.channels_box.value()

    @property
    def frequency(self) -> int:
        return self.frequency_box.value()

    @property
    def add_decoders(self) -> bool:
        return self.pattern == SimulationPattern.PROTOCOLS and self.decoders_box.isChecked()

    def _refresh(self) -> None:
        limits = self.driver.get_limits(list(range(self.channel_count)))
        self.samples_box.setRange(
            max(limits.min_post_samples, 100), max(limits.max_post_samples, limits.min_post_samples, 100)
        )
        self.description.setText(simulation.describe(self.pattern, self.channel_count, self.frequency))
        self.decoders_box.setEnabled(self.pattern == SimulationPattern.PROTOCOLS)

    def build_session(self) -> CaptureSession:
        names = PROTOCOL_CHANNEL_NAMES if self.pattern == SimulationPattern.PROTOCOLS else []
        session = CaptureSession(
            frequency=self.frequency,
            pre_trigger_samples=0,
            post_trigger_samples=self.samples_box.value(),
            trigger_type=TriggerType.SIMULATION,
            trigger_pattern=int(self.pattern),
        )
        session.capture_channels = [
            AnalyzerChannel(channel_number=index, channel_name=names[index] if index < len(names) else "")
            for index in range(self.channel_count)
        ]
        return session

    def _accept(self) -> None:
        self.session = self.build_session()
        self.accept()
